"""SAML signature verification tests — REAL crypto, not mocks.

Principle 3: do NOT mock the thing you're verifying. The prior version
of this test (in a different repo copy) mocked xmlsec/python3-saml/lxml
with MagicMock and hardcoded verify→True. It proved nothing. This version
uses real fixtures: a real self-signed cert, a real XML-DSig signed SAML
response, and real xmlsec verification.

Fixtures generated by /home/z/my-project/scripts/gen_saml_fixtures.py:
- idp.crt / idp.key — real RSA 2048 self-signed cert
- signed_response.xml — real SAML Response with real enveloped RSA-SHA256 signature
- tampered_response.xml — signed then email changed (verification MUST fail)
- unsigned_response.xml — no signature (MUST be rejected)
"""

from __future__ import annotations

import base64
import os
import pathlib

import pytest

FIXTURE_DIR = pathlib.Path(__file__).parent / "fixtures"
CERT_PATH = FIXTURE_DIR / "idp.crt"
SIGNED_PATH = FIXTURE_DIR / "signed_response.xml"
TAMPERED_PATH = FIXTURE_DIR / "tampered_response.xml"
UNSIGNED_PATH = FIXTURE_DIR / "unsigned_response.xml"


@pytest.fixture(autouse=True)
def _clear_saml_env():
    old = os.environ.pop("MAESTRO_SAML_IDP_CERT", None)
    yield
    if old is not None:
        os.environ["MAESTRO_SAML_IDP_CERT"] = old


def _b64(path: pathlib.Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def _make_manager():
    from unittest.mock import MagicMock
    from maestro_auth.saml import SAMLManager, SAMLProviderConfig
    mgr = SAMLManager(store=MagicMock(), sp_base_url="https://maestro.local")
    mgr.get_config = MagicMock(return_value=SAMLProviderConfig(
        name="test", entity_id="https://idp.example.com",
        sso_url="https://idp.example.com/sso", cert=CERT_PATH.read_text(),
    ))
    return mgr


def test_fixtures_exist():
    """All fixtures must be present (generated by scripts/gen_saml_fixtures.py)."""
    for p in [CERT_PATH, SIGNED_PATH, TAMPERED_PATH, UNSIGNED_PATH]:
        assert p.exists(), f"Missing {p}. Run scripts/gen_saml_fixtures.py"


def test_missing_signature_rejected():
    """A SAML response with no signature must be rejected (fail-closed)."""
    from maestro_auth.saml import SAMLError
    with pytest.raises(SAMLError, match="no signature"):
        _make_manager().parse_response("test", _b64(UNSIGNED_PATH))


def test_missing_idp_cert_rejected():
    """A signed response with no MAESTRO_SAML_IDP_CERT set must be rejected."""
    from maestro_auth.saml import SAMLError
    with pytest.raises(SAMLError, match="MAESTRO_SAML_IDP_CERT"):
        _make_manager().parse_response("test", _b64(SIGNED_PATH))


class TestRealCryptoVerification:
    """Real xmlsec against real signed fixtures. Skips if xmlsec/lxml missing."""

    @pytest.fixture(autouse=True)
    def _require_xmlsec(self):
        pytest.importorskip("xmlsec")
        pytest.importorskip("lxml")

    @pytest.fixture(autouse=True)
    def _set_cert(self):
        os.environ["MAESTRO_SAML_IDP_CERT"] = CERT_PATH.read_text()
        yield

    def test_signed_response_verifies_and_extracts_email(self):
        """The core test: a genuinely signed SAML response must verify and
        extract the email. If anything in the verification path is broken,
        this test fails. Principle 1: executed, not read."""
        result = _make_manager().parse_response("test", _b64(SIGNED_PATH))
        assert result is not None
        assert result["email"] == "user@example.com"
        assert result["raw_name_id"] == "user@example.com"

    def test_tampered_response_rejected(self):
        """A signed response modified after signing MUST be rejected.
        Principle 3: this uses a real tampered fixture, not a mock of failure."""
        from maestro_auth.saml import SAMLError
        with pytest.raises(SAMLError, match="verification FAILED|fail-closed"):
            _make_manager().parse_response("test", _b64(TAMPERED_PATH))

    def test_wrong_cert_rejected(self):
        """A signature verified against the wrong cert must be rejected."""
        from maestro_auth.saml import SAMLError
        import subprocess, tempfile
        with tempfile.TemporaryDirectory() as tmp:
            wrong = pathlib.Path(tmp) / "wrong.crt"
            subprocess.run([
                "openssl", "req", "-x509", "-newkey", "rsa:2048",
                "-keyout", str(pathlib.Path(tmp) / "k.key"),
                "-out", str(wrong), "-days", "1", "-nodes",
                "-subj", "/CN=Wrong",
            ], check=True, capture_output=True)
            os.environ["MAESTRO_SAML_IDP_CERT"] = wrong.read_text()
            with pytest.raises(SAMLError, match="verification FAILED|fail-closed"):
                _make_manager().parse_response("test", _b64(SIGNED_PATH))
