#!/usr/bin/env python3
"""test_classifier_goldset.py — Run the taxonomy gold-set against the classifier.

Auditor Principle 3 (2026-07-24): "Gate every merge on the classifier passing
the generated set — the same gold-set/ablation discipline you already use for
the Gold-150 benchmark, applied to the classifier."

This script:
  1. Loads ops/classifier_goldset.json (generated by generate_classifier_goldset.py)
  2. Runs each case through _rule_based_classify (the rules-fallback classifier)
  3. Asserts the classification matches the expected type
  4. Reports pass/fail per category + overall

USAGE:
    python3 ops/test_classifier_goldset.py
    (exit 0 = all cases pass, exit 1 = regression detected)

CI INTEGRATION:
    Runs in .github/workflows/permanence-gate.yml as a correctness gate.
    A merge that breaks the classifier will fail CI.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Add the source path
sys.path.insert(0, str(Path(__file__).parent.parent / "maestro-personal" / "src"))

from maestro_personal_shell.commitment_classifier import _rule_based_classify


def load_goldset() -> list[dict]:
    """Load the generated gold-set."""
    goldset_path = Path(__file__).parent / "classifier_goldset.json"
    if not goldset_path.exists():
        # Generate it if it doesn't exist
        print("Gold-set not found — generating...")
        import importlib.util
        spec = importlib.util.spec_from_file_location("gen", Path(__file__).parent / "generate_classifier_goldset.py")
        gen = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(gen)
        gen.main()
    with open(goldset_path) as f:
        return json.load(f)


def run_goldset() -> dict:
    """Run all gold-set cases and return a report."""
    cases = load_goldset()
    results = {
        "total": len(cases),
        "passed": 0,
        "failed": 0,
        "by_category": {},
        "failures": [],
    }

    for case in cases:
        text = case["text"]
        expected_type = case["expected_type"]
        expected_is_commitment = case["expected_is_commitment"]
        category = case["category"]

        result = _rule_based_classify(text, "Test Entity")
        actual_type = result["commitment_type"]
        actual_is_commitment = result["is_commitment"]

        # The assertion: the type must match. is_commitment is a secondary
        # check — some edge cases may differ on is_commitment but the TYPE
        # must be correct.
        ok = (actual_type == expected_type)

        if category not in results["by_category"]:
            results["by_category"][category] = {"passed": 0, "failed": 0}
        if ok:
            results["passed"] += 1
            results["by_category"][category]["passed"] += 1
        else:
            results["failed"] += 1
            results["by_category"][category]["failed"] += 1
            results["failures"].append({
                "text": text[:100],
                "expected": expected_type,
                "actual": actual_type,
                "category": category,
                "reasoning": case.get("reasoning", ""),
            })

    return results


def main():
    print("=" * 72)
    print("CLASSIFIER GOLD-SET — taxonomy correctness gate")
    print("(Generated cross-product: mood × polarity × tense × ambiguous-words)")
    print("=" * 72)

    report = run_goldset()

    print(f"\nTotal cases: {report['total']}")
    print(f"Passed: {report['passed']}")
    print(f"Failed: {report['failed']}")

    print(f"\nBy category:")
    for cat, counts in sorted(report["by_category"].items()):
        total = counts["passed"] + counts["failed"]
        pct = (counts["passed"] / total * 100) if total > 0 else 0
        icon = "✓" if counts["failed"] == 0 else "✗"
        print(f"  {icon} {cat:40s} {counts['passed']:4d}/{total:4d} ({pct:.1f}%)")

    if report["failures"]:
        print(f"\nFirst 10 failures:")
        for f in report["failures"][:10]:
            print(f"  ✗ [{f['category']}] expected={f['expected']}, actual={f['actual']}")
            print(f"    text: {f['text']}")

    print(f"\n{'='*72}")
    if report["failed"] == 0:
        print(f"✅ GOLD-SET PASSED — {report['passed']}/{report['total']} cases correct")
    else:
        print(f"❌ GOLD-SET FAILED — {report['failed']} regression(s) detected")
    print(f"{'='*72}")

    sys.exit(0 if report["failed"] == 0 else 1)


if __name__ == "__main__":
    main()
